services:
  db:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3307:3306'
    expose:
      - 3307
    volumes:
      - myDbs:/var/lib/mysql
    networks:
      - unified
volumes:
  myDbs:
networks:
  unified:
    name: unified
